{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.port }}
    protocol: TCP
  selector:
    app: user-service
{{- end }}