apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: {{ .Values.global.namespace }}
data:
  environment: {{ .Values.global.environment }}
  domain: {{ .Values.global.domain }}
  timestamp: {{ now | quote }}